Releases/1.7.0
rwth-acis/las2peer-social-bot-manager-service pull request #223
Opened 2023-09-25 20:09 UTC by samuelvkwong

- Able to enhance messages using OpenAI by using the personalize function of the OpenAI wrapper service https://github.com/rwth-acis/las2peer-openai-service
An example set up of the bot model: 
![image](https://github.com/rwth-acis/las2peer-social-bot-manager-service/assets/130673431/ef548c88-e2c8-421a-a550-faafcd58a793)
When the Bot is being parsed, a flag is set in the IncomingMessage to indicate that the bot response should be enhanced by openAI if the Bot Action’s service name is “openai” and function name is “personalize”.
The “model” Action Parameter contains the id of the model to use, in most cases this should be "gpt-3.5-turbo"
The “messages” Action Parameter is empty and has child attributes, which tells the SBF manager that it should be treated as a list.
The “message” Action Parameter is also empty and its child attributes “role” and “content” contain the initial parameters to be passed to OpenAI in a chat completion. For personalizing the bot response, it is ideal if the “role” is “system” and “content” is something like “You personalize and return the last example assistant message”.
https://github.com/rwth-acis/las2peer-social-bot-manager-service/issues/193
- Bot actions can trigger another bot action, meaning the text response from the first bot action can be passed to the second bot action. For example, a response from a bot action can be passed to the personalize function of the OpenAI wrapper service. https://github.com/rwth-acis/las2peer-social-bot-manager-service/issues/208
- Bot actions can lead to an incoming message so that if a request fails the state is not automatically advanced and errors can be handled appropriately. https://github.com/rwth-acis/Social-Bot-Framework/issues/101

2023-09-27 17:09 UTC, lakhoune requested changes

2023-10-05 12:47 UTC, samuelvkwong commented on social-bot-manager/src/main/java/i5/las2peer/services/socialBotManagerService/SocialBotManagerService.java
> +	private static String webconnectorUrlStatic; // address of running webconnector
Not sure, the static one is only used here:
https://github.com/rwth-acis/las2peer-social-bot-manager-service/blob/d4d5ffdfbacb2be26387b1e880faadbfce2dd5e3/social-bot-manager/src/main/java/i5/las2peer/services/socialBotManagerService/SocialBotManagerService.java#L581-L582C21

2023-10-05 12:48 UTC, samuelvkwong commented on social-bot-manager/src/main/java/i5/las2peer/services/socialBotManagerService/SocialBotManagerService.java
> +		if (webconnectorUrl == null || webconnectorUrl.equals("")) {
Okay will remove it

2023-10-05 13:08 UTC, samuelvkwong commented on social-bot-manager/src/main/java/i5/las2peer/services/socialBotManagerService/SocialBotManagerService.java
> +	private static String webconnectorUrlStatic; // address of running webconnector
The method requires a static instance of the webconnectorUrl

2023-10-05 13:17 UTC, merged